# Generated by Django 2.2.5 on 2019-10-27 03:43

from django.db import migrations, models
import videos.models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(upload_to=videos.models.get_video_filename, validators=[videos.models.validate_file_extension], verbose_name='video'),
        ),
    ]
