# Generated by Django 2.2.5 on 2019-10-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20191020_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
