# Generated by Django 2.2.5 on 2019-10-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.TextField()),
                ('q2', models.TextField()),
                ('q3', models.TextField()),
                ('q4', models.TextField()),
                ('q5', models.TextField()),
                ('q6', models.TextField()),
                ('q7', models.TextField()),
                ('q8', models.TextField()),
                ('q9', models.TextField()),
                ('q10', models.TextField()),
                ('q11', models.TextField()),
                ('q12', models.TextField()),
                ('q13', models.TextField()),
                ('q14', models.TextField()),
            ],
        ),
    ]
