# Generated by Django 2.2.5 on 2019-11-29 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='face',
            old_name='first_name',
            new_name='name',
        ),
    ]
