# Generated by Django 2.2.5 on 2019-11-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('count', models.IntegerField(default=0)),
                ('rate', models.FloatField(default=0)),
                ('rate_total', models.FloatField(default=0)),
                ('rate_num', models.IntegerField(default=0)),
            ],
        ),
    ]
