# Generated by Django 2.2.5 on 2019-11-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0004_auto_20191127_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='body',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
