# Generated by Django 2.2.5 on 2019-11-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0005_auto_20191128_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
