# Generated by Django 2.2.5 on 2019-11-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0008_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='rating',
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(default='', max_length=200),
        ),
    ]
