# Generated by Django 2.2.5 on 2019-10-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0002_post_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.CharField(max_length=4000),
        ),
    ]
