# Generated by Django 2.2.5 on 2019-10-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0003_auto_20191027_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
