# Generated by Django 2.2.5 on 2019-10-29 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0004_post_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='rate_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='rate_total',
            field=models.FloatField(default=0),
        ),
    ]
