# Generated by Django 2.2.5 on 2019-11-24 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0005_auto_20191029_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
